import type { AdminRoom } from './types'

const roomHero = '/images/band-room-hero.png'

export const MOCK_ADMIN_ROOMS: AdminRoom[] = [
  {
    id: 'room-001',
    code: 'STD-A1',
    name: 'Studio A1',
    category: 'standard',
    categoryLabel: 'Standard Practice',
    capacity: 4,
    pricePerHour: 120000,
    status: 'active',
    image: roomHero,
    equipmentCount: 6,
    equipments: ['Drum kit Pearl', 'Marshall combo amp', 'Bass amp', 'Keyboard 61 keys', '2 microphones', 'Mixer 8 channels'],
    todaySchedule: '09:00-11:00, 18:00-20:00',
    lastUpdated: '27/06/2026 09:15',
    description: 'Phòng tập tiêu chuẩn cho nhóm nhỏ, cách âm tốt và bố trí gọn để setup nhanh.',
    occupancyRateToday: 62,
    monthlyRevenue: 18400000,
    averageRating: 4.6,
    latestMaintenance: 'Vệ sinh acoustic panel - 20/06/2026',
  },
  {
    id: 'room-002',
    code: 'STD-A2',
    name: 'Studio A2',
    category: 'standard',
    categoryLabel: 'Standard Practice',
    capacity: 5,
    pricePerHour: 135000,
    status: 'occupied',
    image: roomHero,
    equipmentCount: 7,
    equipments: ['Drum kit Mapex', '2 guitar amps', 'Bass amp', 'Monitor speaker', '3 microphones', 'Mixer 10 channels'],
    todaySchedule: '10:00-12:00, 15:00-17:00, 19:00-21:00',
    lastUpdated: '27/06/2026 10:45',
    description: 'Không gian linh hoạt cho band indie, có monitor riêng cho vocalist.',
    occupancyRateToday: 78,
    monthlyRevenue: 21150000,
    averageRating: 4.7,
    latestMaintenance: 'Kiểm tra ampli guitar - 18/06/2026',
  },
  {
    id: 'room-003',
    code: 'STD-A3',
    name: 'Studio A3',
    category: 'standard',
    categoryLabel: 'Standard Practice',
    capacity: 4,
    pricePerHour: 120000,
    status: 'maintenance',
    image: roomHero,
    equipmentCount: 5,
    equipments: ['Drum kit Tama', 'Guitar amp', 'Bass amp', '2 microphones', 'Audio interface'],
    todaySchedule: 'Đang khóa lịch',
    lastUpdated: '26/06/2026 18:20',
    description: 'Phòng đang bảo trì hệ thống điện và kiểm tra cách âm cửa.',
    occupancyRateToday: 0,
    monthlyRevenue: 15600000,
    averageRating: 4.4,
    latestMaintenance: 'Bảo trì điện phòng - 27/06/2026',
  },
  {
    id: 'room-004',
    code: 'BAND-B1',
    name: 'Band Room B1',
    category: 'band',
    categoryLabel: 'Band Rehearsal',
    capacity: 7,
    pricePerHour: 180000,
    status: 'active',
    image: roomHero,
    equipmentCount: 10,
    equipments: ['Full drum kit', '2 Marshall stacks', 'Ampeg bass head', 'Keyboard 88 keys', 'PA system', '4 microphones'],
    todaySchedule: '08:00-10:00, 14:00-16:00',
    lastUpdated: '27/06/2026 08:30',
    description: 'Phòng rehearsal rộng cho band 5-7 người, phù hợp luyện live set.',
    occupancyRateToday: 54,
    monthlyRevenue: 32600000,
    averageRating: 4.8,
    latestMaintenance: 'Thay dây snare - 21/06/2026',
  },
  {
    id: 'room-005',
    code: 'BAND-B2',
    name: 'Band Room B2',
    category: 'band',
    categoryLabel: 'Band Rehearsal',
    capacity: 8,
    pricePerHour: 195000,
    status: 'occupied',
    image: roomHero,
    equipmentCount: 11,
    equipments: ['Drum kit DW', 'Mesa guitar amp', 'Fender guitar amp', 'Bass cabinet', 'Digital mixer', '5 microphones'],
    todaySchedule: '11:00-13:00, 16:00-18:00, 20:00-22:00',
    lastUpdated: '27/06/2026 11:05',
    description: 'Phòng có hệ thống PA mạnh, thường được đặt cho buổi tổng duyệt.',
    occupancyRateToday: 83,
    monthlyRevenue: 38450000,
    averageRating: 4.9,
    latestMaintenance: 'Cân chỉnh PA - 19/06/2026',
  },
  {
    id: 'room-006',
    code: 'BAND-B3',
    name: 'Band Room B3',
    category: 'band',
    categoryLabel: 'Band Rehearsal',
    capacity: 6,
    pricePerHour: 170000,
    status: 'active',
    image: roomHero,
    equipmentCount: 9,
    equipments: ['Drum kit Yamaha', '2 guitar amps', 'Bass amp', 'Keyboard 61 keys', 'PA speaker pair', '3 microphones'],
    todaySchedule: '13:00-15:00, 18:00-19:00',
    lastUpdated: '26/06/2026 16:40',
    description: 'Phòng band tầm trung, setup cân bằng cho luyện tập hằng tuần.',
    occupancyRateToday: 47,
    monthlyRevenue: 27800000,
    averageRating: 4.5,
    latestMaintenance: 'Kiểm tra dây tín hiệu - 17/06/2026',
  },
  {
    id: 'room-007',
    code: 'REC-C1',
    name: 'Recording C1',
    category: 'recording',
    categoryLabel: 'Recording Suite',
    capacity: 5,
    pricePerHour: 260000,
    status: 'active',
    image: roomHero,
    equipmentCount: 14,
    equipments: ['Control desk', 'Nearfield monitors', 'Condenser mic', 'Audio interface', 'Vocal booth', 'Headphone amp'],
    todaySchedule: '09:00-12:00, 17:00-19:00',
    lastUpdated: '27/06/2026 07:50',
    description: 'Phòng thu có booth riêng, phù hợp thu vocal, demo và podcast âm nhạc.',
    occupancyRateToday: 58,
    monthlyRevenue: 42600000,
    averageRating: 4.8,
    latestMaintenance: 'Calibrate monitor - 16/06/2026',
  },
  {
    id: 'room-008',
    code: 'REC-C2',
    name: 'Recording C2',
    category: 'recording',
    categoryLabel: 'Recording Suite',
    capacity: 4,
    pricePerHour: 240000,
    status: 'inactive',
    image: roomHero,
    equipmentCount: 12,
    equipments: ['Audio interface', 'Monitor speakers', 'Dynamic mic set', 'Vocal shield', 'MIDI keyboard', 'Headphones'],
    todaySchedule: 'Tạm ngưng nhận lịch',
    lastUpdated: '25/06/2026 14:10',
    description: 'Phòng đang tạm ngưng để nâng cấp phần mềm thu âm và hệ thống patch bay.',
    occupancyRateToday: 0,
    monthlyRevenue: 30100000,
    averageRating: 4.3,
    latestMaintenance: 'Nâng cấp DAW - 25/06/2026',
  },
  {
    id: 'room-009',
    code: 'REC-C3',
    name: 'Recording C3',
    category: 'recording',
    categoryLabel: 'Recording Suite',
    capacity: 6,
    pricePerHour: 280000,
    status: 'active',
    image: roomHero,
    equipmentCount: 15,
    equipments: ['Large diaphragm mic', 'Preamp rack', 'Monitor controller', 'Drum mic kit', 'Studio headphones', 'MIDI controller'],
    todaySchedule: '12:00-15:00',
    lastUpdated: '26/06/2026 20:05',
    description: 'Phòng thu lớn hơn cho live session, có bộ mic drum và preamp rack.',
    occupancyRateToday: 42,
    monthlyRevenue: 46800000,
    averageRating: 4.7,
    latestMaintenance: 'Vệ sinh mic drum kit - 22/06/2026',
  },
  {
    id: 'room-010',
    code: 'PRE-D1',
    name: 'Premium D1',
    category: 'premium',
    categoryLabel: 'Premium Studio',
    capacity: 9,
    pricePerHour: 340000,
    status: 'active',
    image: roomHero,
    equipmentCount: 18,
    equipments: ['Premium drum kit', 'Tube amps', 'Full PA', 'Stage lights', 'Recording interface', 'In-ear monitor system'],
    todaySchedule: '10:00-12:00, 19:00-22:00',
    lastUpdated: '27/06/2026 12:00',
    description: 'Studio cao cấp cho rehearsal, quay clip performance và showcase nhỏ.',
    occupancyRateToday: 72,
    monthlyRevenue: 58800000,
    averageRating: 4.9,
    latestMaintenance: 'Kiểm tra ánh sáng sân khấu - 23/06/2026',
  },
  {
    id: 'room-011',
    code: 'PRE-D2',
    name: 'Premium D2',
    category: 'premium',
    categoryLabel: 'Premium Studio',
    capacity: 10,
    pricePerHour: 360000,
    status: 'occupied',
    image: roomHero,
    equipmentCount: 20,
    equipments: ['DW Collector drum kit', 'Kemperor amp', 'Ampeg SVT', 'Digital console', 'Stage monitor set', 'Video lighting kit'],
    todaySchedule: '08:00-11:00, 14:00-17:00, 18:00-20:00',
    lastUpdated: '27/06/2026 12:35',
    description: 'Phòng lớn nhất cho band đông thành viên, có console số và ánh sáng hỗ trợ quay dựng.',
    occupancyRateToday: 88,
    monthlyRevenue: 64200000,
    averageRating: 4.9,
    latestMaintenance: 'Firmware digital console - 24/06/2026',
  },
  {
    id: 'room-012',
    code: 'PRE-D3',
    name: 'Premium D3',
    category: 'premium',
    categoryLabel: 'Premium Studio',
    capacity: 8,
    pricePerHour: 320000,
    status: 'maintenance',
    image: roomHero,
    equipmentCount: 17,
    equipments: ['Premium PA', 'Tube guitar amps', 'Bass stack', 'Synth station', 'Wireless mic set', 'Camera-ready lighting'],
    todaySchedule: 'Đang khóa lịch',
    lastUpdated: '26/06/2026 09:25',
    description: 'Đang bảo trì hệ thống ánh sáng và thay jack patch cho khu vực control.',
    occupancyRateToday: 0,
    monthlyRevenue: 51200000,
    averageRating: 4.6,
    latestMaintenance: 'Thay jack patch bay - 27/06/2026',
  },
]
