import type { AdminEquipment } from './types'

export const MOCK_ADMIN_EQUIPMENT: AdminEquipment[] = [
  {
    equipmentId: 'eq-001',
    equipmentCode: 'TB-001',
    equipmentName: 'Marshall MG30 Guitar Amp',
    equipmentType: 'AMPLIFIER',
    quantity: 4,
    availableQuantity: 2,
    rentalPrice: 80_000,
    status: 'AVAILABLE',
    description: 'Amp guitar 30W, phù hợp tập nhóm nhỏ.',
    imageUrl: '/images/equipment/marshall-mg30.jpg',
    inActiveBooking: false,
  },
  {
    equipmentId: 'eq-002',
    equipmentCode: 'TB-002',
    equipmentName: 'Pearl Export Drum Kit',
    equipmentType: 'DRUM',
    quantity: 2,
    availableQuantity: 0,
    rentalPrice: 200_000,
    status: 'IN_USE',
    description: 'Bộ trống Pearl Export đầy đủ cymbal.',
    imageUrl: '/images/equipment/pearl-drums.jpg',
    inActiveBooking: true,
  },
  {
    equipmentId: 'eq-003',
    equipmentCode: 'TB-003',
    equipmentName: 'Yamaha P-125 Digital Piano',
    equipmentType: 'KEYBOARD',
    quantity: 3,
    availableQuantity: 3,
    rentalPrice: 120_000,
    status: 'AVAILABLE',
    description: 'Piano điện 88 phím weighted.',
    inActiveBooking: false,
  },
  {
    equipmentId: 'eq-004',
    equipmentCode: 'TB-004',
    equipmentName: 'Fender Stratocaster',
    equipmentType: 'GUITAR',
    quantity: 5,
    availableQuantity: 4,
    rentalPrice: 100_000,
    status: 'AVAILABLE',
    description: 'Guitar điện Fender Strat, dây mới.',
    inActiveBooking: false,
  },
  {
    equipmentId: 'eq-005',
    equipmentCode: 'TB-005',
    equipmentName: 'Shure SM58 Micro',
    equipmentType: 'MICROPHONE',
    quantity: 8,
    availableQuantity: 6,
    rentalPrice: 50_000,
    status: 'AVAILABLE',
    description: 'Micro dynamic cổ điển cho vocal.',
    inActiveBooking: false,
  },
  {
    equipmentId: 'eq-006',
    equipmentCode: 'TB-006',
    equipmentName: 'KRK Rokit 5 Monitor',
    equipmentType: 'MONITOR',
    quantity: 4,
    availableQuantity: 2,
    rentalPrice: 90_000,
    status: 'IN_USE',
    description: 'Loa monitor studio cặp.',
    inActiveBooking: true,
  },
  {
    equipmentId: 'eq-007',
    equipmentCode: 'TB-007',
    equipmentName: 'Focusrite Scarlett 2i2',
    equipmentType: 'RECORDING',
    quantity: 2,
    availableQuantity: 0,
    rentalPrice: 150_000,
    status: 'MAINTENANCE',
    description: 'Audio interface thu âm 2 input.',
    inActiveBooking: false,
  },
  {
    equipmentId: 'eq-008',
    equipmentCode: 'TB-008',
    equipmentName: 'Behringer X32 Mixer',
    equipmentType: 'AMPLIFIER',
    quantity: 1,
    availableQuantity: 0,
    rentalPrice: 350_000,
    status: 'DISABLED',
    description: 'Mixer digital 32 kênh — tạm ngưng cho thuê.',
    inActiveBooking: false,
  },
]
