CREATE TYPE IF NOT EXISTS role AS ENUM ('CUSTOMER', 'STAFF', 'ADMIN');
CREATE TYPE IF NOT EXISTS room_status AS ENUM ('AVAILABLE', 'IN_USE', 'MAINTENANCE');
CREATE TYPE IF NOT EXISTS booking_status AS ENUM (
    'PENDING_PAYMENT',
    'PAID',
    'CHECKED_IN',
    'COMPLETED',
    'CANCELLED'
);
CREATE TYPE IF NOT EXISTS payment_method AS ENUM ('CASH', 'ONLINE');
CREATE TYPE IF NOT EXISTS payment_provider AS ENUM ('VNPAY');
CREATE TYPE IF NOT EXISTS payment_transaction_status AS ENUM (
    'INITIALIZED',
    'PENDING',
    'SUCCEEDED',
    'FAILED',
    'CANCELLED'
);
