-- CANH BAO: Script nay xoa toan bo schema public cua database bandlabdb.
-- Hay kiem tra dung connection 127.0.0.1:6789/bandlabdb truoc khi chay.

BEGIN;

DO $$
BEGIN
  IF current_database() <> 'bandlabdb' THEN
    RAISE EXCEPTION
      'Dung script: database hien tai la %, khong phai bandlabdb',
      current_database();
  END IF;
END
$$;

DROP EXTENSION IF EXISTS btree_gist CASCADE;
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT USAGE ON SCHEMA public TO PUBLIC;

CREATE EXTENSION btree_gist;

CREATE TYPE "vai_tro" AS ENUM (
  'CUSTOMER',
  'STAFF',
  'ADMIN'
);

CREATE TYPE "trang_thai_phong" AS ENUM (
  'TRONG',
  'DANG_DUNG',
  'BAO_TRI'
);

CREATE TYPE "trang_thai_dat_phong" AS ENUM (
  'CHO_THANH_TOAN',
  'DA_THANH_TOAN',
  'DA_CHECKIN',
  'HOAN_TAT',
  'DA_HUY'
);

CREATE TYPE "phuong_thuc_thanh_toan" AS ENUM (
  'TIEN_MAT',
  'ONLINE'
);

CREATE TYPE "loai_giam_gia" AS ENUM (
  'PHAN_TRAM',
  'SO_TIEN'
);

CREATE TYPE "trang_thai_ca" AS ENUM (
  'DA_PHAN',
  'DANG_LAM',
  'HOAN_TAT'
);

CREATE TYPE "loai_thiet_bi" AS ENUM (
  'AMP',
  'MIXER',
  'MIC',
  'TRONG',
  'GUITAR',
  'KEYBOARD',
  'KHAC'
);

CREATE TYPE "trang_thai_thiet_bi" AS ENUM (
  'TOT',
  'HONG',
  'BAO_TRI'
);

CREATE TABLE "tai_khoan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "mat_khau_hash" varchar NOT NULL,
  "vai_tro" vai_tro NOT NULL,
  "reset_token" varchar UNIQUE,
  "reset_token_expires_at" timestamp,
  "ngay_tao" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "revoked_token" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token_hash" varchar(64) UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "khach_hang" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tai_khoan_id" int UNIQUE NOT NULL,
  "ho_ten" varchar NOT NULL,
  "so_dien_thoai" varchar,
  "email" varchar,
  "ngay_sinh" date
);

CREATE TABLE "nhan_vien" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tai_khoan_id" int UNIQUE NOT NULL,
  "ho_ten" varchar NOT NULL,
  "so_dien_thoai" varchar,
  "email" varchar,
  "ngay_sinh" date
);

CREATE TABLE "hang_phong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_hang" varchar UNIQUE NOT NULL,
  "gia_gio" numeric(12,2) NOT NULL,
  "mo_ta" text,
  CONSTRAINT "chk_hang_phong_gia_gio_duong" CHECK ("gia_gio" > 0)
);

CREATE TABLE "phong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten" varchar UNIQUE NOT NULL,
  "hang_phong_id" int NOT NULL,
  "trang_thai" trang_thai_phong NOT NULL DEFAULT 'TRONG'
);

CREATE TABLE "thiet_bi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phong_id" int NOT NULL,
  "loai" loai_thiet_bi NOT NULL,
  "ten" varchar NOT NULL,
  "trang_thai" trang_thai_thiet_bi NOT NULL DEFAULT 'TOT',
  "ghi_chu" text
);

CREATE TABLE "ma_giam_gia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma" varchar UNIQUE NOT NULL,
  "loai" loai_giam_gia NOT NULL,
  "gia_tri" numeric(12,2) NOT NULL,
  "dieu_kien_min" numeric(12,2),
  "ngay_het_han" date,
  CONSTRAINT "chk_ma_giam_gia_gia_tri_duong" CHECK ("gia_tri" > 0),
  CONSTRAINT "chk_ma_giam_gia_phan_tram" CHECK (
    "loai" <> 'PHAN_TRAM' OR "gia_tri" <= 100
  ),
  CONSTRAINT "chk_ma_giam_gia_dieu_kien_min" CHECK (
    "dieu_kien_min" IS NULL OR "dieu_kien_min" >= 0
  )
);

CREATE TABLE "dat_phong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "khach_hang_id" int NOT NULL,
  "phong_id" int NOT NULL,
  "ma_giam_gia_id" int,
  "nhan_vien_checkin_id" int,
  "gio_bat_dau" timestamp NOT NULL,
  "gio_ket_thuc" timestamp NOT NULL,
  "gio_checkin" timestamp,
  "gio_checkout" timestamp,
  "phuong_thuc" phuong_thuc_thanh_toan NOT NULL,
  "gia_gio_ap_dung" numeric(12,2) NOT NULL,
  "tong_tien" numeric(12,2) NOT NULL,
  "trang_thai" trang_thai_dat_phong NOT NULL DEFAULT 'CHO_THANH_TOAN',
  "ghi_chu_nhac_cu" varchar(500),
  "ghi_chu" varchar(500),
  "ngay_tao" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "chk_dat_phong_khoang_thoi_gian" CHECK (
    "gio_bat_dau" < "gio_ket_thuc"
  ),
  CONSTRAINT "chk_dat_phong_gia_gio_ap_dung" CHECK (
    "gia_gio_ap_dung" > 0
  ),
  CONSTRAINT "chk_dat_phong_tong_tien" CHECK ("tong_tien" >= 0),
  CONSTRAINT "chk_dat_phong_checkin_checkout" CHECK (
    "gio_checkout" IS NULL
    OR ("gio_checkin" IS NOT NULL AND "gio_checkin" <= "gio_checkout")
  )
);

CREATE TABLE "lich_su_trang_thai_dat_phong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dat_phong_id" int NOT NULL,
  "trang_thai_cu" trang_thai_dat_phong,
  "trang_thai_moi" trang_thai_dat_phong NOT NULL,
  "ghi_chu" varchar(500),
  "thoi_gian" timestamp NOT NULL DEFAULT (now()),
  "thuc_hien_boi" int
);

CREATE TABLE "danh_gia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dat_phong_id" int UNIQUE NOT NULL,
  "diem" int NOT NULL,
  "noi_dung" text,
  "da_duyet" boolean NOT NULL DEFAULT true,
  "ngay_tao" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "chk_danh_gia_diem" CHECK ("diem" BETWEEN 1 AND 5)
);

CREATE TABLE "ca_lam" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nhan_vien_id" int NOT NULL,
  "ngay" date NOT NULL,
  "gio_bat_dau" time NOT NULL,
  "gio_ket_thuc" time NOT NULL,
  "trang_thai" trang_thai_ca NOT NULL DEFAULT 'DA_PHAN',
  "diem_chat_luong" int,
  CONSTRAINT "chk_ca_lam_khoang_thoi_gian" CHECK (
    "gio_bat_dau" < "gio_ket_thuc"
  ),
  CONSTRAINT "chk_ca_lam_diem_chat_luong" CHECK (
    "diem_chat_luong" IS NULL OR "diem_chat_luong" BETWEEN 1 AND 5
  )
);

CREATE INDEX "idx_thiet_bi_phong_loai"
  ON "thiet_bi" ("phong_id", "loai");

CREATE INDEX "idx_dat_phong_phong_thoi_gian"
  ON "dat_phong" ("phong_id", "gio_bat_dau", "gio_ket_thuc");

CREATE INDEX "idx_dat_phong_khach_hang_ngay_tao"
  ON "dat_phong" ("khach_hang_id", "ngay_tao" DESC);

CREATE INDEX "idx_dat_phong_trang_thai_gio_bat_dau"
  ON "dat_phong" ("trang_thai", "gio_bat_dau");

CREATE INDEX "idx_lich_su_dat_phong_thoi_gian"
  ON "lich_su_trang_thai_dat_phong" ("dat_phong_id", "thoi_gian");

CREATE INDEX "idx_ca_lam_nhan_vien_ngay"
  ON "ca_lam" ("nhan_vien_id", "ngay");

CREATE INDEX "idx_revoked_token_expires_at"
  ON "revoked_token" ("expires_at");

ALTER TABLE "dat_phong"
  ADD CONSTRAINT "excl_dat_phong_khong_trung_lich"
  EXCLUDE USING gist (
    "phong_id" WITH =,
    tsrange("gio_bat_dau", "gio_ket_thuc", '[)') WITH &&
  )
  WHERE ("trang_thai" <> 'DA_HUY');

ALTER TABLE "ca_lam"
  ADD CONSTRAINT "excl_ca_lam_nhan_vien_khong_trung"
  EXCLUDE USING gist (
    "nhan_vien_id" WITH =,
    tsrange("ngay" + "gio_bat_dau", "ngay" + "gio_ket_thuc", '[)') WITH &&
  );

COMMENT ON COLUMN "hang_phong"."gia_gio" IS 'Giá thuê / giờ';

COMMENT ON COLUMN "thiet_bi"."ten" IS 'Tên/model cụ thể, vd: Marshall MG30, Shure SM58';

COMMENT ON COLUMN "ma_giam_gia"."dieu_kien_min" IS 'Giá trị đơn tối thiểu';

COMMENT ON COLUMN "dat_phong"."ma_giam_gia_id" IS 'Có thể null';

COMMENT ON COLUMN "dat_phong"."nhan_vien_checkin_id" IS 'NV xử lý check-in, có thể null';

COMMENT ON COLUMN "dat_phong"."gia_gio_ap_dung" IS 'Giá giờ tại thời điểm đặt';

COMMENT ON COLUMN "dat_phong"."ghi_chu_nhac_cu" IS 'Nhạc cụ/thiết bị của phòng khách muốn dùng để nhân viên chuẩn bị';

COMMENT ON COLUMN "dat_phong"."ghi_chu" IS 'Ghi chú khác của khách hoặc nhân viên';

COMMENT ON COLUMN "lich_su_trang_thai_dat_phong"."thuc_hien_boi" IS 'tai_khoan.id của người thực hiện thay đổi; null nếu do hệ thống tự động';

COMMENT ON COLUMN "danh_gia"."diem" IS '1-5';

COMMENT ON COLUMN "ca_lam"."diem_chat_luong" IS 'Admin đánh giá ca, 1-5';

ALTER TABLE "khach_hang" ADD FOREIGN KEY ("tai_khoan_id") REFERENCES "tai_khoan" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "nhan_vien" ADD FOREIGN KEY ("tai_khoan_id") REFERENCES "tai_khoan" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phong" ADD FOREIGN KEY ("hang_phong_id") REFERENCES "hang_phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "thiet_bi" ADD FOREIGN KEY ("phong_id") REFERENCES "phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dat_phong" ADD FOREIGN KEY ("khach_hang_id") REFERENCES "khach_hang" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dat_phong" ADD FOREIGN KEY ("phong_id") REFERENCES "phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dat_phong" ADD FOREIGN KEY ("ma_giam_gia_id") REFERENCES "ma_giam_gia" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dat_phong" ADD FOREIGN KEY ("nhan_vien_checkin_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lich_su_trang_thai_dat_phong" ADD FOREIGN KEY ("dat_phong_id") REFERENCES "dat_phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lich_su_trang_thai_dat_phong" ADD FOREIGN KEY ("thuc_hien_boi") REFERENCES "tai_khoan" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "danh_gia" ADD FOREIGN KEY ("dat_phong_id") REFERENCES "dat_phong" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ca_lam" ADD FOREIGN KEY ("nhan_vien_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

COMMIT;
