-- Coupon usage tracking and SePay provider support.

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_provider') THEN
        ALTER TYPE payment_provider ADD VALUE IF NOT EXISTS 'SEPAY';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS coupon_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_code_id INT NOT NULL REFERENCES discount_code(id),
    customer_id INT NOT NULL REFERENCES customer(id),
    booking_id INT NOT NULL UNIQUE REFERENCES booking(id),
    discount_amount NUMERIC(12,2) NOT NULL CHECK (discount_amount >= 0),
    used_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_coupon_usage_discount_code_used_at
    ON coupon_usage(discount_code_id, used_at);

CREATE INDEX IF NOT EXISTS idx_coupon_usage_customer_used_at
    ON coupon_usage(customer_id, used_at);
