-- Bootstrap missing repo-owned PostgreSQL schema additions before Hibernate validates.
-- This keeps local development databases aligned with the latest migrations when they
-- are only missing the recent payment/coupon/support tables.

ALTER TABLE account
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS email_verification_token_hash VARCHAR(64),
    ADD COLUMN IF NOT EXISTS email_verification_expires_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS email_verification_sent_at TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS ux_account_email_verification_token_hash
    ON account(email_verification_token_hash)
    WHERE email_verification_token_hash IS NOT NULL;

UPDATE account
SET email_verified = true
WHERE email_verified = false
  AND email_verification_token_hash IS NULL
  AND email_verification_expires_at IS NULL;

ALTER TYPE payment_provider ADD VALUE IF NOT EXISTS 'SEPAY';
ALTER TYPE payment_provider ADD VALUE IF NOT EXISTS 'COUNTER';

CREATE TABLE IF NOT EXISTS customer_issue_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES customer(id),
    booking_id INT REFERENCES booking(id),
    issue_type VARCHAR(30) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_customer_issue_report_issue_type
        CHECK (issue_type IN ('ROOM', 'EQUIPMENT', 'PAYMENT', 'ACCOUNT', 'OTHER')),
    CONSTRAINT chk_customer_issue_report_status
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
    CONSTRAINT chk_customer_issue_report_description_not_blank
        CHECK (btrim(description) <> '')
);

CREATE INDEX IF NOT EXISTS idx_customer_issue_report_customer_created_at
    ON customer_issue_report (customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_customer_issue_report_booking_id
    ON customer_issue_report (booking_id);

CREATE TABLE IF NOT EXISTS coupon_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_code_id INT NOT NULL REFERENCES discount_code(id),
    customer_id INT NOT NULL REFERENCES customer(id),
    booking_id INT NOT NULL UNIQUE REFERENCES booking(id),
    discount_amount NUMERIC(12,2) NOT NULL CHECK (discount_amount >= 0),
    used_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_coupon_usage_discount_code_used_at
    ON coupon_usage(discount_code_id, used_at);

CREATE INDEX IF NOT EXISTS idx_coupon_usage_customer_used_at
    ON coupon_usage(customer_id, used_at);
